

log4j.logger.com.unionpay=DEBUG,STDOUT,UAS_SDK_LOG,STDOUT,UAS_SDK_ERR_LOG

log4j.appender.STDOUT=org.apache.log4j.ConsoleAppender
log4j.appender.STDOUT.ImmediateFlush=true
log4j.appender.STDOUT.layout=org.apache.log4j.PatternLayout
log4j.appender.STDOUT.layout.ConversionPattern=[%d{HH:mm:ss}|%-5p|(%c)]: %m%n

log4j.appender.UAS_SDK_LOG=org.apache.log4j.DailyRollingFileAppender
log4j.appender.UAS_SDK_LOG.Threshold=DEBUG
log4j.appender.UAS_SDK_LOG.ImmediateFlush=true
log4j.appender.UAS_SDK_LOG.DatePattern='.'yyyy-MM-dd
log4j.appender.UAS_SDK_LOG.File=logs/uassdk.log
log4j.appender.UAS_SDK_LOG.layout=org.apache.log4j.PatternLayout
log4j.appender.UAS_SDK_LOG.layout.ConversionPattern=[(%d{yyyyMMddHHmmss})|(%c)]=[%m]%n

log4j.appender.UAS_SDK_ERR_LOG=org.apache.log4j.DailyRollingFileAppender
log4j.appender.UAS_SDK_ERR_LOG.Threshold=ERROR
log4j.appender.UAS_SDK_ERR_LOG.ImmediateFlush=true
log4j.appender.UAS_SDK_ERR_LOG.DatePattern='.'yyyy-MM-dd
log4j.appender.UAS_SDK_ERR_LOG.File=logs/uassdk-error.log
log4j.appender.UAS_SDK_ERR_LOG.layout=org.apache.log4j.PatternLayout
log4j.appender.UAS_SDK_ERR_LOG.layout.ConversionPattern=[(%d{yyyyMMddHHmmss})|(%c)]=[%m]%n