##############SDK配置文件（证书方式签名）################
# 说明：
# 1. 使用时请将此文件复制到src文件夹下替换原来的uas_sdk.properties。
# 2. 具体配置项请根据注释修改。
#
################################################

##########################入网测试环境交易发送地址（线上测试需要使用生产环境交易请求地址）#############################

uassdk.transUrl=http://172.21.224.202:8080/test/trans.do

########################################################################

# 是否验证验签证书的CN，测试环境请设置false，生产环境请设置true。非false的值默认都当true处理。
uassdk.ifValidateCNName=false


#########################入网测试环境签名证书配置 ################################
# 多证书的情况证书路径为代码指定，可不对此块做配置。
# 签名证书路径，必须使用绝对路径，如果不想使用绝对路径，可以自行实现相对路径获取证书的方法；测试证书所有商户共用开发包中的测试签名证书
# windows样例：
uassdk.signCert.path=d:/uas_certs/RSA/ATRsa.pfx
uassdk.sm2.signCert.path=d:/uas_certs/SM2/sm2_dev_pm_pri.sm2
# linux样例（注意：在linux下读取证书需要保证证书有被应用读的权限）（后续其他路径配置也同此条说明）
#uassdk.signCert.path=/SERVICE01/usr/ac_frnas/conf/sign.pfx

##########################证书密码配置################################
# 签名证书密码
uassdk.signCert.pwd=123456
uassdk.sm2.signCert.pwd=cfca1234

#########################解密证书配置 ################################
uassdk.decryptCert.path=d:/uas_certs/RSA/ATRsa.pfx
uassdk.sm2.decryptCert.path=d:/uas_certs/SM2/sm2_dev_pm_pri.sm2
# 解密证书密码
uassdk.decryptCert.pwd=123456
uassdk.sm2.decryptCert.pwd=cfca1234

## 以下是配多套证书的示例
## 解密证书可以配置最多十套 decryptCert ~ decryptCert9；根据银联返回的encryptData域里的certId字段匹配对应证书
#uassdk.decryptCert1.path=d:/uas_certs/RSA/ATRsa.pfx
#uassdk.sm2.decryptCert1.path=d:/uas_certs/SM2/sm2_dev_pm_pri.sm2
#uassdk.decryptCert1.pwd=123456
#uassdk.sm2.decryptCert1.pwd=cfca1234
#
#uassdk.decryptCert2.path=d:/uas_certs/RSA/ATRsa.pfx
#uassdk.sm2.decryptCert2.path=d:/uas_certs/SM2/sm2_dev_pm_pri.sm2
#uassdk.decryptCert2.pwd=123456
#uassdk.sm2.decryptCert2.pwd=cfca1234
#
#uassdk.decryptCert3.path=d:/uas_certs/RSA/ATRsa.pfx
#uassdk.sm2.decryptCert3.path=d:/uas_certs/SM2/sm2_dev_pm_pri.sm2
#uassdk.decryptCert3.pwd=123456
#uassdk.sm2.decryptCert3.pwd=cfca1234
# ......

##########################加密证书配置################################
# 敏感信息加密证书路径
uassdk.encryptCert.path=d:/uas_certs/RSA/ATRsa.cer
uassdk.sm2.encryptCert.path=d:/uas_certs/SM2/ATSm2.cer
# pin加密证书路径
uassdk.pinEncryptCert.path=d:/uas_certs/RSA/ATRsa.cer
uassdk.sm2.pinEncryptCert.path=d:/uas_certs/SM2/ATSm2.cer

##########################验签证书配置################################
# 验签证书路径(银联提供)
uassdk.validateCert.dir=d:/uas_certs/RSA/
uassdk.sm2.validateCert.dir=d:/uas_certs/SM2/

# 验签中级证书路径(银联提供)
uassdk.middleCert.path=d:/uas_certs/RSA/acp_test_middle.cer
uassdk.sm2.middleCert.path=d:/uas_certs/SM2/acp_test_middle.cer

# 验签根证书路径(银联提供)
uassdk.rootCert.path=d:/uas_certs/RSA/acp_test_root.cer
uassdk.sm2.rootCert.path=d:/uas_certs/SM2/acp_test_middle.cer

# 是否需要验证公钥证书链 默认打开(true)
need.verify.pubkey=true